name: first workflow
on: push
jobs:
    ASCII_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: list files
          run: ls -lrt

        - name: execute shell script
          run: |
              chmod +x command.sh
              ./command.sh  



        # - name: execute all commands
        #   run: |
        #     echo ¨my first Github action¨
        #     ls -lrt
        #     cat .gitignore

        # - name: install cowsay package
        #   run: sudo apt-get install cowsay -y    
        
        # - name: generate ASCII art
        #   run: cowsay -f dragon 

        # - name: list files
        #   run: ls -lrt

        # - name: view the file
        #   run: cat .gitignore